name: quizz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/films.png
    - assets/images/technologies.png
    - assets/images/history.png
    - assets/images/math.png
    - assets/images/football.png
    - assets/images/geography.png
  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBM_Plex_Mono/Bold.ttf
        - asset: assets/fonts/IBM_Plex_Mono/Light.ttf
        - asset: assets/fonts/IBM_Plex_Mono/Medium.ttf
        - asset: assets/fonts/IBM_Plex_Mono/Regular.ttf
        - asset: assets/fonts/IBM_Plex_Mono/SemiBold.ttf
        - asset: assets/fonts/IBM_Plex_Mono/Thin.ttf