name: quizz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/films.png
    - assets/images/technologies.png
    - assets/images/history.png
    - assets/images/math.png
    - assets/images/football.png
    - assets/images/geography.png
